apiVersion: v1
kind: Namespace
metadata:
  name: media
---
# ========= SHARED STORAGE (RWX via NFS) =========
# This backs /data for all apps. If you already have a dynamic RWX class (e.g., Longhorn NFS),
# you can skip the PV and create a PVC with that storageClass instead.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-data-pv
spec:
  capacity:
    storage: 5Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""   # static PV (no storageClass)
  mountOptions:
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - noatime
    - nconnect=4
  nfs:
    server: 10.0.0.10            # <-- CHANGE ME
    path: /export/media          # <-- CHANGE ME
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-data-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Ti
  storageClassName: ""
  volumeName: media-data-pv
---
# ========= PER-APP CONFIG PVCs (RWO on Longhorn) =========
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-pvc
  namespace: media
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-pvc
  namespace: media
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config-pvc
  namespace: media
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config-pvc
  namespace: media
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyseerr-config-pvc
  namespace: media
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
---
# ========= OPTIONAL: Put common env into a ConfigMap =========
apiVersion: v1
kind: ConfigMap
metadata:
  name: media-common-env
  namespace: media
data:
  TZ: Europe/Amsterdam        # <-- CHANGE if needed
  PUID: "1000"                # <-- CHANGE to your uid
  PGID: "1000"                # <-- CHANGE to your gid
---
# ========= JELLYFIN =========
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: media
  labels: { app: jellyfin }
spec:
  replicas: 1
  selector: { matchLabels: { app: jellyfin } }
  template:
    metadata:
      labels: { app: jellyfin }
    spec:
      containers:
      - name: jellyfin
        image: ghcr.io/linuxserver/jellyfin:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          valueFrom: { configMapKeyRef: { name: media-common-env, key: TZ } }
        - name: PUID
          valueFrom: { configMapKeyRef: { name: media-common-env, key: PUID } }
        - name: PGID
          valueFrom: { configMapKeyRef: { name: media-common-env, key: PGID } }
        - name: JELLYFIN_PublishedServerUrl
          value: "jellyfin.example.com"    # <-- or your LB IP; used by clients for external URL
        ports:
        - { name: http,  containerPort: 8096, protocol: TCP }
        - { name: https, containerPort: 8920, protocol: TCP }
        # DLNA/Discovery (UDP) are exposed via a separate Service below
        volumeMounts:
        - { name: config, mountPath: /config }
        - { name: media,  mountPath: /data }
        # If you use a downloads directory, mount it as /downloads as well
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            memory: "2Gi"
      volumes:
      - name: config
        persistentVolumeClaim: { claimName: jellyfin-config-pvc }
      - name: media
        persistentVolumeClaim: { claimName: media-data-pvc }
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: media
  labels: { app: jellyfin }
spec:
  selector: { app: jellyfin }
  type: ClusterIP
  ports:
  - name: http
    port: 8096
    targetPort: 8096
  - name: https
    port: 8920
    targetPort: 8920
---
# OPTIONAL: DLNA/Discovery on LAN (MetalLB). Remove if you don't need DLNA.
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-udp
  namespace: media
  annotations:
    metallb.universe.tf/allow-shared-ip: jellyfin
spec:
  selector: { app: jellyfin }
  type: LoadBalancer
  loadBalancerIP: 172.16.23.35     # <-- CHANGE/REMOVE if not reserving a static IP
  sessionAffinity: ClientIP
  ports:
  - { name: dlna-udp,      port: 1900, targetPort: 1900, protocol: UDP }
  - { name: discovery-udp, port: 7359, targetPort: 7359, protocol: UDP }
---
# ========= RADARR =========
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: media
  labels: { app: radarr }
spec:
  replicas: 1
  selector: { matchLabels: { app: radarr } }
  template:
    metadata:
      labels: { app: radarr }
    spec:
      containers:
      - name: radarr
        image: ghcr.io/linuxserver/radarr:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          valueFrom: { configMapKeyRef: { name: media-common-env, key: TZ } }
        - name: PUID
          valueFrom: { configMapKeyRef: { name: media-common-env, key: PUID } }
        - name: PGID
          valueFrom: { configMapKeyRef: { name: media-common-env, key: PGID } }
        ports:
        - { name: http, containerPort: 7878 }
        volumeMounts:
        - { name: config, mountPath: /config }
        - { name: media,  mountPath: /data }
      volumes:
      - name: config
        persistentVolumeClaim: { claimName: radarr-config-pvc }
      - name: media
        persistentVolumeClaim: { claimName: media-data-pvc }
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: media
spec:
  selector: { app: radarr }
  type: ClusterIP
  ports:
  - { name: http, port: 7878, targetPort: 7878 }
---
# ========= SONARR =========
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: media
  labels: { app: sonarr }
spec:
  replicas: 1
  selector: { matchLabels: { app: sonarr } }
  template:
    metadata:
      labels: { app: sonarr }
    spec:
      containers:
      - name: sonarr
        image: ghcr.io/linuxserver/sonarr:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          valueFrom: { configMapKeyRef: { name: media-common-env, key: TZ } }
        - name: PUID
          valueFrom: { configMapKeyRef: { name: media-common-env, key: PUID } }
        - name: PGID
          valueFrom: { configMapKeyRef: { name: media-common-env, key: PGID } }
        ports:
        - { name: http, containerPort: 8989 }
        volumeMounts:
        - { name: config, mountPath: /config }
        - { name: media,  mountPath: /data }
      volumes:
      - name: config
        persistentVolumeClaim: { claimName: sonarr-config-pvc }
      - name: media
        persistentVolumeClaim: { claimName: media-data-pvc }
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: media
spec:
  selector: { app: sonarr }
  type: ClusterIP
  ports:
  - { name: http, port: 8989, targetPort: 8989 }
---
# ========= BAZARR =========
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
  namespace: media
  labels: { app: bazarr }
spec:
  replicas: 1
  selector: { matchLabels: { app: bazarr } }
  template:
    metadata:
      labels: { app: bazarr }
    spec:
      containers:
      - name: bazarr
        image: ghcr.io/linuxserver/bazarr:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          valueFrom: { configMapKeyRef: { name: media-common-env, key: TZ } }
        - name: PUID
          valueFrom: { configMapKeyRef: { name: media-common-env, key: PUID } }
        - name: PGID
          valueFrom: { configMapKeyRef: { name: media-common-env, key: PGID } }
        ports:
        - { name: http, containerPort: 6767 }
        volumeMounts:
        - { name: config, mountPath: /config }
        - { name: media,  mountPath: /data }
      volumes:
      - name: config
        persistentVolumeClaim: { claimName: bazarr-config-pvc }
      - name: media
        persistentVolumeClaim: { claimName: media-data-pvc }
---
apiVersion: v1
kind: Service
metadata:
  name: bazarr
  namespace: media
spec:
  selector: { app: bazarr }
  type: ClusterIP
  ports:
  - { name: http, port: 6767, targetPort: 6767 }
---
# ========= JELLYSEERR =========
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseerr
  namespace: media
  labels: { app: jellyseerr }
spec:
  replicas: 1
  selector: { matchLabels: { app: jellyseerr } }
  template:
    metadata:
      labels: { app: jellyseerr }
    spec:
      containers:
      - name: jellyseerr
        image: fallenbagel/jellyseerr:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          valueFrom: { configMapKeyRef: { name: media-common-env, key: TZ } }
        - name: LOG_LEVEL
          value: info
        ports:
        - { name: http, containerPort: 5055 }
        volumeMounts:
        - { name: config, mountPath: /app/config }
      volumes:
      - name: config
        persistentVolumeClaim: { claimName: jellyseerr-config-pvc }
---
apiVersion: v1
kind: Service
metadata:
  name: jellyseerr
  namespace: media
spec:
  selector: { app: jellyseerr }
  type: ClusterIP
  ports:
  - { name: http, port: 5055, targetPort: 5055 }
---
# ========= INGRESS (NGINX + cert-manager) =========
# Point each host to your DNS A/AAAA for your ingress controller's external IP.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: media-ingress
  namespace: media
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"   # <-- ensure this exists
spec:
  tls:
  - hosts:
      - jellyfin.example.com
      - radarr.example.com
      - sonarr.example.com
      - bazarr.example.com
      - requests.example.com
    secretName: media-wildcard-tls
  rules:
  - host: jellyfin.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: { name: jellyfin, port: { number: 8096 } }
  - host: radarr.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: { name: radarr, port: { number: 7878 } }
  - host: sonarr.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: { name: sonarr, port: { number: 8989 } }
  - host: bazarr.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: { name: bazarr, port: { number: 6767 } }
  - host: requests.example.com   # Jellyseerr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: { name: jellyseerr, port: { number: 5055 } }
