apiVersion: v1
kind: Namespace
metadata:
  name: jellyfin
---
# ===================== PVCs binding to your existing Longhorn PVs =====================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-pvc
  namespace: jellyfin
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: "longhorn"
  resources:
    requests:
      storage: 5Gi
  volumeName: "jellyfin-config-pv"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-pvc
  namespace: jellyfin
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: "longhorn"
  resources:
    requests:
      storage: 5Gi
  volumeName: "radarr-config-pv"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config-pvc
  namespace: jellyfin
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: "longhorn"
  resources:
    requests:
      storage: 5Gi
  volumeName: "sonarr-config-pv"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config-pvc
  namespace: jellyfin
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: "longhorn"
  resources:
    requests:
      storage: 5Gi
  volumeName: "bazarr-config-pv"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyseerr-config-pvc
  namespace: jellyfin
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: "longhorn"
  resources:
    requests:
      storage: 5Gi
  volumeName: "jellyseerr-config-pv"
---
# ===================== JELLYFIN =====================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: jellyfin
  labels: { app: jellyfin }
spec:
  replicas: 1
  selector: { matchLabels: { app: jellyfin } }
  template:
    metadata:
      labels: { app: jellyfin }
    spec:
      volumes:
      - name: jellyfin-config
        persistentVolumeClaim:
          claimName: jellyfin-config-pvc
      - name: media
        hostPath:
          path: /data-nfs/data/plex
          type: Directory
      containers:
      - name: jellyfin
        image: ghcr.io/linuxserver/jellyfin:latest
        imagePullPolicy: IfNotPresent
        env:
        - { name: JELLYFIN_PublishedServerUrl, value: "172.16.23.35" }
        - { name: PUID, value: "1044" }
        - { name: PGID, value: "65541" }
        - { name: TZ,   value: "Europe/Amsterdam" }
        securityContext:
          privileged: true   # remove if you don't need HW acceleration
        ports:
        - { name: http,  containerPort: 8096, protocol: TCP }
        - { name: https, containerPort: 8920, protocol: TCP }
        - { name: dlna-udp, containerPort: 1900, protocol: UDP }
        - { name: discovery-udp, containerPort: 7359, protocol: UDP }
        volumeMounts:
        - { name: jellyfin-config, mountPath: /config }
        - { name: media,          mountPath: /data }
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-tcp
  namespace: jellyfin
  annotations:
    metallb.universe.tf/allow-shared-ip: media-stack
spec:
  selector: { app: jellyfin }
  type: LoadBalancer
  loadBalancerIP: "172.16.23.35"
  sessionAffinity: ClientIP
  ports:
  - { name: jellyfin-http,  port: 8096, targetPort: 8096, protocol: TCP }
  - { name: jellyfin-https, port: 8920, targetPort: 8920, protocol: TCP }
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-udp
  namespace: jellyfin
  annotations:
    metallb.universe.tf/allow-shared-ip: media-stack
spec:
  selector: { app: jellyfin }
  type: LoadBalancer
  loadBalancerIP: "172.16.23.35"
  sessionAffinity: ClientIP
  ports:
  - { name: dlna-udp,      port: 1900, targetPort: 1900, protocol: UDP }
  - { name: discovery-udp, port: 7359, targetPort: 7359, protocol: UDP }
---
# ===================== RADARR =====================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: jellyfin
  labels: { app: radarr }
spec:
  replicas: 1
  selector: { matchLabels: { app: radarr } }
  template:
    metadata:
      labels: { app: radarr }
    spec:
      volumes:
      - name: radarr-config
        persistentVolumeClaim:
          claimName: radarr-config-pvc
      - name: media
        hostPath:
          path: /data-nfs/data/plex
          type: Directory
      containers:
      - name: radarr
        image: ghcr.io/linuxserver/radarr:latest
        imagePullPolicy: IfNotPresent
        env:
        - { name: PUID, value: "1044" }
        - { name: PGID, value: "65541" }
        - { name: TZ,   value: "Europe/Amsterdam" }
        ports:
        - { name: http, containerPort: 7878 }
        volumeMounts:
        - { name: radarr-config, mountPath: /config }
        - { name: media,         mountPath: /data }
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: jellyfin
  annotations:
    metallb.universe.tf/allow-shared-ip: media-stack
spec:
  selector: { app: radarr }
  type: LoadBalancer
  loadBalancerIP: "172.16.23.35"
  sessionAffinity: ClientIP
  ports:
  - { name: radarr-http, port: 7878, targetPort: 7878, protocol: TCP }
---
# ===================== SONARR =====================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: jellyfin
  labels: { app: sonarr }
spec:
  replicas: 1
  selector: { matchLabels: { app: sonarr } }
  template:
    metadata:
      labels: { app: sonarr }
    spec:
      volumes:
      - name: sonarr-config
        persistentVolumeClaim:
          claimName: sonarr-config-pvc
      - name: media
        hostPath:
          path: /data-nfs/data/plex
          type: Directory
      containers:
      - name: sonarr
        image: ghcr.io/linuxserver/sonarr:latest
        imagePullPolicy: IfNotPresent
        env:
        - { name: PUID, value: "1044" }
        - { name: PGID, value: "65541" }
        - { name: TZ,   value: "Europe/Amsterdam" }
        ports:
        - { name: http, containerPort: 8989 }
        volumeMounts:
        - { name: sonarr-config, mountPath: /config }
        - { name: media,         mountPath: /data }
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: jellyfin
  annotations:
    metallb.universe.tf/allow-shared-ip: media-stack
spec:
  selector: { app: sonarr }
  type: LoadBalancer
  loadBalancerIP: "172.16.23.35"
  sessionAffinity: ClientIP
  ports:
  - { name: sonarr-http, port: 8989, targetPort: 8989, protocol: TCP }
---
# ===================== BAZARR =====================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
  namespace: jellyfin
  labels: { app: bazarr }
spec:
  replicas: 1
  selector: { matchLabels: { app: bazarr } }
  template:
    metadata:
      labels: { app: bazarr }
    spec:
      volumes:
      - name: bazarr-config
        persistentVolumeClaim:
          claimName: bazarr-config-pvc
      - name: media
        hostPath:
          path: /data-nfs/data/plex
          type: Directory
      containers:
      - name: bazarr
        image: ghcr.io/linuxserver/bazarr:latest
        imagePullPolicy: IfNotPresent
        env:
        - { name: PUID, value: "1044" }
        - { name: PGID, value: "65541" }
        - { name: TZ,   value: "Europe/Amsterdam" }
        ports:
        - { name: http, containerPort: 6767 }
        volumeMounts:
        - { name: bazarr-config, mountPath: /config }
        - { name: media,         mountPath: /data }
---
apiVersion: v1
kind: Service
metadata:
  name: bazarr
  namespace: jellyfin
  annotations:
    metallb.universe.tf/allow-shared-ip: media-stack
spec:
  selector: { app: bazarr }
  type: LoadBalancer
  loadBalancerIP: "172.16.23.35"
  sessionAffinity: ClientIP
  ports:
  - { name: bazarr-http, port: 6767, targetPort: 6767, protocol: TCP }
---
# ===================== JELLYSEERR =====================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseerr
  namespace: jellyfin
  labels: { app: jellyseerr }
spec:
  replicas: 1
  selector: { matchLabels: { app: jellyseerr } }
  template:
    metadata:
      labels: { app: jellyseerr }
    spec:
      volumes:
      - name: jellyseerr-config
        persistentVolumeClaim:
          claimName: jellyseerr-config-pvc
      containers:
      - name: jellyseerr
        image: fallenbagel/jellyseerr:latest
        imagePullPolicy: IfNotPresent
        env:
        - { name: TZ,        value: "Europe/Amsterdam" }
        - { name: LOG_LEVEL, value: "info" }
        ports:
        - { name: http, containerPort: 5055 }
        volumeMounts:
        - { name: jellyseerr-config, mountPath: /app/config }
---
apiVersion: v1
kind: Service
metadata:
  name: jellyseerr
  namespace: jellyfin
  annotations:
    metallb.universe.tf/allow-shared-ip: media-stack
spec:
  selector: { app: jellyseerr }
  type: LoadBalancer
  loadBalancerIP: "172.16.23.35"
  sessionAffinity: ClientIP
  ports:
  - { name: jellyseerr-http, port: 5055, targetPort: 5055, protocol: TCP }
